name: My Workflow
on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'A sample input'
        required: true

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello, ${{ github.event.inputs.my_input }}"
