name: My Workflow

on:
  push:
    branches: [main]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input
        run: echo "The input value is ${{ inputs.my_input }}"
        env:
          INPUT_MY_INPUT: ${{ github.event.inputs.my_input }}

